import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import { ReduxProvider } from "@/redux/store";
import SideBar from "@/app/_common/SideBar/SideBar";
import MusicPlayer from "@/app/_common/MusicPlayer/MusicPlayer";
import { useAppSelector } from "@/redux/hooks";

const inter = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chupi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="App">
            <SideBar />
            <div className="main">
              {children}
              <MusicPlayer />
            </div>
            <div className="background"></div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
